### ISSUE TITLE
Error message when opening Visual Studio without any solution

### ISSUE THREAD

**Issue by didierdonner** [ashmind/SolutionIcon#4]
Hello,

I would like to report a small issue. When opening Visual Studio 2017 without a solution opened, I get the following errors in the output window:
Solution '' opened.
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at AshMind.IO.Abstractions.Adapters.FileSystem.GetFile(String path)
   at SolutionIcon.Implementation.IconFinder.FindIcon(Solution solution)
   at SolutionIcon.Implementation.SolutionIconManager.FindAndConvertExistingIcon(Solution solution)
   at SolutionIcon.Implementation.SolutionIconManager.GetIcon(Solution solution)
   at SolutionIcon.Implementation.SolutionIconManager.SolutionEvents_Opened()

This is a very minor bug that does not prevent the usage of that extension that is invaluable when three or more instances of VS 2017 with solution are opened. I just happen to use VS 2017 as a code editor (when I could be using Visual Studio Code, Notepad++, Notepad2 ...)

Best regards,

Didier Donner

**Comment by didierdonner** [comment]
Here is the attached patch after getting the code via SVN

[SolutionIconManager.cs.txt](https://github.com/ashmind/SolutionIcon/files/918984/SolutionIconManager.cs.txt)

One day, I will learn the Zen of Git.

**Comment by ashmind** [comment]
@didierdonner Thanks! I'll try to merge this tomorrow.
