### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by Spoelle** [ashmind/SolutionIcon#6]
Your extension is a very good idea ! But I got an issue on Windows7 / V Studio 2015 Professional

Output window when opening a solution:

Solution 'ServiceCenter.Electro' opened.
Solution 'ServiceCenter.Electro': found icon at 'C:\Development\VB.Net\Krefel\Applications\ServiceCenter.Electro\favicon.ico'.
System.InvalidOperationException: A valid active Window is needed to update the Taskbar.
   at Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.get_OwnerHandle()
   at Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.SetOverlayIcon(Icon icon, String accessibilityText)
   at SolutionIcon.Implementation.SolutionIconManager.SolutionEvents_Opened()

Thanks, Luc

**Comment by Spoelle** [comment]
I did some more tests and put a ico file named ".editoricon.ico" in the solution root. Output window:
Solution 'ServiceCenter.Electro' opened.
Solution 'ServiceCenter.Electro': found icon at 'C:\Development\VB.Net\Krefel\Applications\ServiceCenter.Electro\\.editoricon.ico'.

But no icon...

![image](https://cloud.githubusercontent.com/assets/19902865/26342433/561faf42-3f98-11e7-8398-800ee2e6dd7c.png)

**Comment by ashmind** [comment]
Thanks for reporting this. Are you using small taskbar icons?
Unfortunately this extension does not support small icons due to limitations of Windows, see #2.

**Comment by ygoe** [comment]
I, too, have an icon that fails to show now. I've opened that solution before, and with this extension, I saw a generated icon with the solution's capital letters. After adding a .editoricon.png file like I successfully did in 2 other solutions, it doesn't show up here. Not after restarting VS. It's also 32x32 pixels as both others. Created with the same software (paint.net). I still see the generated icon with the letters. Is it cached somewhere? Where can I find out why it's not showing?

**Comment by ygoe** [comment]
I converted the .png into a .ico, with the same size, only 32x32, and that works. The .png not.
